import {
  DirectionEnum,
  PostTypeEnum,
  IPost,
  PostStatus,
  ExpertStatus,
} from '../../../../lib/types';

const NEWEST_POSTS_DATA_MOCK: IPost[] = [
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '301445431956241',
      photo: 'https://i.pravatar.cc/100?img=1',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.CARDIOLOGY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '301445431956242',
      photo: 'https://i.pravatar.cc/100?img=2',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.PEDIATRICS,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.VIDEO,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '301445431956243',
      photo: 'https://i.pravatar.cc/100?img=3',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.COVID19,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '301445431956244',
      photo: 'https://i.pravatar.cc/100?img=4',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.COVID19,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.DOPYS,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '301445431956245',
      photo: 'https://i.pravatar.cc/100?img=5',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '301445431956246',
      photo: 'https://i.pravatar.cc/100?img=6',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '301445431956247',
      photo: 'https://i.pravatar.cc/100?img=7',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '301445431956248',
      photo: 'https://i.pravatar.cc/100?img=8',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '301445431956249',
      photo: 'https://i.pravatar.cc/100?img=9',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562410',
      photo: 'https://i.pravatar.cc/100?img=10',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562411',
      photo: 'https://i.pravatar.cc/100?img=11',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562412',
      photo: 'https://i.pravatar.cc/100?img=12',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562413',
      photo: 'https://i.pravatar.cc/100?img=13',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562414',
      photo: 'https://i.pravatar.cc/100?img=14',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562415',
      photo: 'https://i.pravatar.cc/100?img=15',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562416',
      photo: 'https://i.pravatar.cc/100?img=16',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562417',
      photo: 'https://i.pravatar.cc/100?img=17',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562418',
      photo: 'https://i.pravatar.cc/100?img=18',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562419',
      photo: 'https://i.pravatar.cc/100?img=19',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562420',
      photo: 'https://i.pravatar.cc/100?img=20',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562421',
      photo: 'https://i.pravatar.cc/100?img=21',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562422',
      photo: 'https://i.pravatar.cc/100?img=22',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562423',
      photo: 'https://i.pravatar.cc/100?img=23',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562424',
      photo: 'https://i.pravatar.cc/100?img=24',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562425',
      photo: 'https://i.pravatar.cc/100?img=25',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562426',
      photo: 'https://i.pravatar.cc/100?img=26',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562427',
      photo: 'https://i.pravatar.cc/100?img=27',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562428',
      photo: 'https://i.pravatar.cc/100?img=28',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562429',
      photo: 'https://i.pravatar.cc/100?img=29',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562430',
      photo: 'https://i.pravatar.cc/100?img=30',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562431',
      photo: 'https://i.pravatar.cc/100?img=31',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562432',
      photo: 'https://i.pravatar.cc/100?img=32',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562433',
      photo: 'https://i.pravatar.cc/100?img=33',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562434',
      photo: 'https://i.pravatar.cc/100?img=34',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562435',
      photo: 'https://i.pravatar.cc/100?img=35',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562436',
      photo: 'https://i.pravatar.cc/100?img=36',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562437',
      photo: 'https://i.pravatar.cc/100?img=37',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562438',
      photo: 'https://i.pravatar.cc/100?img=38',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562439',
      photo: 'https://i.pravatar.cc/100?img=39',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562440',
      photo: 'https://i.pravatar.cc/100?img=40',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562441',
      photo: 'https://i.pravatar.cc/100?img=41',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562442',
      photo: 'https://i.pravatar.cc/100?img=42',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562443',
      photo: 'https://i.pravatar.cc/100?img=43',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562444',
      photo: 'https://i.pravatar.cc/100?img=44',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562445',
      photo: 'https://i.pravatar.cc/100?img=45',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562446',
      photo: 'https://i.pravatar.cc/100?img=46',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562447',
      photo: 'https://i.pravatar.cc/100?img=47',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562448',
      photo: 'https://i.pravatar.cc/100?img=48',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562449',
      photo: 'https://i.pravatar.cc/100?img=49',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    author: {
      status: ExpertStatus.NEW,
      firstName: 'Ivan',
      secondName: 'Pavlov',
      email: 'pavlov_ivan@gmail.com',
      phone: '3014454319562450',
      photo: 'https://i.pravatar.cc/100?img=50',
      workPlace: 'Kyiv, KMKL #17',
    },
    direction: DirectionEnum.THERAPY,
    title: 'Mock title',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    status: PostStatus.PUBLISHED,
    important: true,
    tags: ['covid19'],
    createdAt: '26.11.2020',
    modifiedAt: '11.12.2020',
    postType: PostTypeEnum.ARTICLE,
    preview:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
];

export default NEWEST_POSTS_DATA_MOCK;
