# build environment
FROM node:13.12.0-alpine as build
WORKDIR /dokazovi-fe
ENV PATH /dokazovi-fe/node_modules/.bin:$PATH
COPY package.json ./
RUN npm install --no-optional
COPY . ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /dokazovi-fe/build /usr/share/nginx/html
# new
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
