export const mockNewestContent = {
  content: [
    {
      fieldName: 'expertOpinion',
      postDTOS: [
        {
          id: 115,
          title: '123',
          preview:
            'cvj;qdksjn;ckjnqsd;jkcvnq;sjdhcfn;wejqnhc;vksdnc;jkasdn;jkfd;skcn',
          content:
            '<p>wejkbv;wejkaqvn;cfkqsdjn;vkjqenw;vknqe;rjkgvnh;qsdjknvc;qweklnv;jqsd</p>',
          videoUrl: null,
          previewImageUrl: 'https://i.imgur.com/1u7sQl2.png',
          author: {
            id: 59,
            firstName: 'Катерина',
            lastName: 'Булавінова',
            avatar: 'https://i.imgur.com/k0j4vVH.png',
            bio: 'медичний експерт ЮНІСЕФ в Україні',
            mainInstitution: {
              id: 10,
              name: 'UNICEF Ukraine',
              city: { id: 190, name: 'Київ' },
            },
          },
          directions: [
            {
              id: 7,
              name: 'pediatrics',
              label: 'Педіатрія',
              color: '#993333',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 1,
              name: 'covid-19',
              label: 'Covid-19',
              color: '#ef5350',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 4,
              name: 'therapy',
              label: 'Терапія',
              color: '#ffee58',
              hasDoctors: true,
              hasPosts: true,
            },
          ],
          tags: [],
          type: { id: 1, name: 'Стаття' },
          status: 'PUBLISHED',
          origins: [{ id: 1, name: 'Думка експерта', parameters: null }],
          createdAt: '25.10.2021',
          modifiedAt: '25.10.2021',
          publishedAt: '25.10.2021',
          importanceOrder: null,
          importantImageUrl: '',
          importantMobileImageUrl: '',
        },
        {
          id: 114,
          title: 'Допис Lorem Ipsum',
          preview:
            'Існує багато варіацій уривків з Lorem Ipsum, але більшість з них зазнала певних змін на кшталт жартівливих вставок або змішування слів, які навіть не виглядають правдоподібно.',
          content:
            '<p class="ql-align-justify">На відміну від поширеної думки Lorem Ipsum не є випадковим набором літер. Він походить з уривку класичної латинської літератури 45 року до н.е., тобто має більш як 2000-річну історію. Річард Макклінток, професор латини з коледжу Хемпдін-Сидні, що у Вірджінії, вивчав одне з найменш зрозумілих латинських слів - consectetur - з уривку Lorem Ipsum, і у пошуку цього слова в класичній літературі знайшов безсумнівне джерело. Lorem Ipsum походить з розділів 1.10.32 та 1.10.33 цицеронівського "de Finibus Bonorum et Malorum" ("Про межі добра і зла"), написаного у 45 році до н.е. Цей трактат з теорії етики був дуже популярним в епоху Відродження. Перший рядок Lorem Ipsum, "Lorem ipsum dolor sit amet..." походить з одного з рядків розділу 1.10.32.</p><p class="ql-align-justify">Класичний текст, використовуваний з XVI сторіччя, наведено нижче для всіх зацікавлених. Також точно за оригіналом наведено розділи 1.10.32 та 1.10.33 цицеронівського "de Finibus Bonorum et Malorum" разом із перекладом англійською, виконаним 1914 року Х.Рекемом.</p><p><br></p><h2>Чому ми ним користуємось?</h2><p class="ql-align-justify">Вже давно відомо, що читабельний зміст буде заважати зосередитись людині, яка оцінює композицію сторінки. Сенс використання Lorem Ipsum полягає в тому, що цей текст має більш-менш нормальне розподілення літер на відміну від, наприклад, "Тут іде текст. Тут іде текст." Це робить текст схожим на оповідний. Багато програм верстування та веб-дизайну використовують Lorem Ipsum як зразок і пошук за терміном "lorem ipsum" відкриє багато веб-сайтів, які знаходяться ще в зародковому стані. Різні версії Lorem Ipsum з\'явились за минулі роки, деякі випадково, деякі було створено зумисно (зокрема, жартівливі).</p><p><br></p><h2>Звідки він походить?</h2><p class="ql-align-justify">На відміну від поширеної думки Lorem Ipsum не є випадковим набором літер. Він походить з уривку класичної латинської літератури 45 року до н.е., тобто має більш як 2000-річну історію. Річард Макклінток, професор латини з коледжу Хемпдін-Сидні, що у Вірджінії, вивчав одне з найменш зрозумілих латинських слів - consectetur - з уривку Lorem Ipsum, і у пошуку цього слова в класичній літературі знайшов безсумнівне джерело. Lorem Ipsum походить з розділів 1.10.32 та 1.10.33 цицеронівського "de Finibus Bonorum et Malorum" ("Про межі добра і зла"), написаного у 45 році до н.е. Цей трактат з теорії етики був дуже популярним в епоху Відродження. Перший рядок Lorem Ipsum, "Lorem ipsum dolor sit amet..." походить з одного з рядків розділу 1.10.32.</p><p class="ql-align-justify">Класичний текст, використовуваний з XVI сторіччя, наведено нижче для всіх зацікавлених. Також точно за оригіналом наведено розділи 1.10.32 та 1.10.33 цицеронівського "de Finibus Bonorum et Malorum" разом із перекладом англійською, виконаним 1914 року Х.Рекемом.</p><h2>Де собі взяти трохи?</h2><p class="ql-align-justify">Існує багато варіацій уривків з Lorem Ipsum, але більшість з них зазнала певних змін на кшталт жартівливих вставок або змішування слів, які навіть не виглядають правдоподібно. Якщо ви збираєтесь використовувати Lorem Ipsum, ви маєте упевнитись в тому, що всередині тексту не приховано нічого, що могло б викликати у читача конфуз. Більшість відомих генераторів Lorem Ipsum в Мережі генерують текст шляхом повторення наперед заданих послідовностей Lorem Ipsum. Принципова відмінність цього генератора робить його першим справжнім генератором Lorem Ipsum. Він використовує словник з більш як 200 слів латини та цілий набір моделей речень - це дозволяє генерувати Lorem Ipsum, який виглядає осмислено. Таким чином, згенерований Lorem Ipsum не міститиме повторів, жартів, нехарактерних для латини слів і т.ін.</p>',
          videoUrl: null,
          previewImageUrl: '',
          author: {
            id: 14,
            firstName: 'Олег',
            lastName: 'Петренко',
            avatar: 'https://i.pravatar.cc/300?img=11',
            bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
            mainInstitution: {
              id: 5,
              name: 'Medical Idea',
              city: { id: 55, name: 'Бровари' },
            },
          },
          directions: [
            {
              id: 5,
              name: 'virology',
              label: 'Вірусологія',
              color: '#da80e8',
              hasDoctors: true,
              hasPosts: true,
            },
          ],
          tags: [],
          type: { id: 3, name: 'Допис' },
          status: 'PUBLISHED',
          origins: [{ id: 1, name: 'Думка експерта', parameters: null }],
          createdAt: '22.10.2021',
          modifiedAt: '22.10.2021',
          publishedAt: '22.10.2021',
          importanceOrder: null,
          importantImageUrl: '',
          importantMobileImageUrl: '',
        },
        {
          id: 89,
          title: 'Tempus quam pellentesque',
          preview:
            'Proin nibh nisl condimentum id venenatis a condimentum vitae.',
          content:
            'Proin nibh nisl condimentum id venenatis a condimentum vitae.',
          videoUrl: '',
          previewImageUrl: '',
          author: {
            id: 13,
            firstName: 'Марина',
            lastName: 'Вовк',
            avatar: 'https://i.pravatar.cc/300?img=5',
            bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
            mainInstitution: {
              id: 1,
              name: 'Адоніс',
              city: { id: 190, name: 'Київ' },
            },
          },
          directions: [
            {
              id: 5,
              name: 'virology',
              label: 'Вірусологія',
              color: '#da80e8',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 6,
              name: 'cardiology',
              label: 'Кардіологія',
              color: '#00ffff',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 4,
              name: 'therapy',
              label: 'Терапія',
              color: '#ffee58',
              hasDoctors: true,
              hasPosts: true,
            },
          ],
          tags: [],
          type: { id: 1, name: 'Стаття' },
          status: 'PUBLISHED',
          origins: [{ id: 1, name: 'Думка експерта', parameters: null }],
          createdAt: '16.02.2021',
          modifiedAt: '16.02.2021',
          publishedAt: '20.10.2021',
          importanceOrder: null,
          importantImageUrl: '',
          importantMobileImageUrl: '',
        },
        {
          id: 82,
          title: 'Sit amet consectetur',
          preview:
            'Varius vel pharetra vel turpis nunc eget. Nisl tincidunt eget nullam non nisi est sit amet facilisis.',
          content:
            'Varius vel pharetra vel turpis nunc eget. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Integer eget aliquet nibh praesent tristique magna sit amet purus. Dolor purus non enim praesent elementum facilisis leo.',
          videoUrl: '',
          previewImageUrl: '',
          author: {
            id: 16,
            firstName: 'Дмитро',
            lastName: 'Степаненко',
            avatar: 'https://i.pravatar.cc/300?img=8',
            bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
            mainInstitution: {
              id: 2,
              name: 'Новий зір',
              city: { id: 190, name: 'Київ' },
            },
          },
          directions: [
            {
              id: 1,
              name: 'covid-19',
              label: 'Covid-19',
              color: '#ef5350',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 3,
              name: 'surgery',
              label: 'Хірургія',
              color: '#7aebbf',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 2,
              name: 'ophthalmology',
              label: 'Офтальмологія',
              color: '#98ef50',
              hasDoctors: true,
              hasPosts: true,
            },
          ],
          tags: [],
          type: { id: 1, name: 'Стаття' },
          status: 'PUBLISHED',
          origins: [{ id: 1, name: 'Думка експерта', parameters: null }],
          createdAt: '16.02.2021',
          modifiedAt: '16.02.2021',
          publishedAt: '20.10.2021',
          importanceOrder: null,
          importantImageUrl: '',
          importantMobileImageUrl: '',
        },
      ],
    },
    {
      fieldName: 'media',
      postDTOS: [
        {
          id: 111,
          title: 'авапвапвапвапвап',
          preview:
            'https://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpghttps://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-l',
          content:
            '<p>https://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpghttps://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpghttps://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpghttps://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpghttps://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpghttps://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpghttps://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpghttps://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpghttps://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpghttps://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpg</p>',
          videoUrl: null,
          previewImageUrl:
            'https://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpg',
          author: {
            id: 56,
            firstName: 'Bill',
            lastName: 'Yamamoto',
            avatar: 'https://i.pravatar.cc/300?img=57',
            bio:
              'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            mainInstitution: {
              id: 8,
              name: 'Поліклінічне об’єднання',
              city: { id: 233, name: 'Луганськ' },
            },
          },
          directions: [
            {
              id: 2,
              name: 'ophthalmology',
              label: 'Офтальмологія',
              color: '#98ef50',
              hasDoctors: true,
              hasPosts: true,
            },
          ],
          tags: [],
          type: { id: 1, name: 'Стаття' },
          status: 'PUBLISHED',
          origins: [{ id: 2, name: 'Медитека', parameters: null }],
          createdAt: '20.10.2021',
          modifiedAt: '20.10.2021',
          publishedAt: '20.10.2021',
          importanceOrder: null,
          importantImageUrl: '',
          importantMobileImageUrl: '',
        },
        {
          id: 90,
          title: 'Ultrices eros in cursus',
          preview:
            'Dolor sit amet consectetur adipiscing elit ut aliquam purus.',
          content:
            'Dolor sit amet consectetur adipiscing elit ut aliquam purus.',
          videoUrl: '',
          previewImageUrl: '',
          author: {
            id: 12,
            firstName: 'Степан',
            lastName: 'Степанов',
            avatar: 'https://i.pravatar.cc/300?img=12',
            bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
            mainInstitution: {
              id: 3,
              name: 'Інномед',
              city: { id: 81, name: 'Вінниця' },
            },
          },
          directions: [
            {
              id: 5,
              name: 'virology',
              label: 'Вірусологія',
              color: '#da80e8',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 7,
              name: 'pediatrics',
              label: 'Педіатрія',
              color: '#993333',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 6,
              name: 'cardiology',
              label: 'Кардіологія',
              color: '#00ffff',
              hasDoctors: true,
              hasPosts: true,
            },
          ],
          tags: [],
          type: { id: 1, name: 'Стаття' },
          status: 'PUBLISHED',
          origins: [{ id: 2, name: 'Медитека', parameters: null }],
          createdAt: '16.02.2021',
          modifiedAt: '16.02.2021',
          publishedAt: '20.10.2021',
          importanceOrder: null,
          importantImageUrl: '',
          importantMobileImageUrl: '',
        },
        {
          id: 85,
          title: 'Tempus quam pellentesque',
          preview:
            'Proin nibh nisl condimentum id venenatis a condimentum vitae.',
          content:
            'Proin nibh nisl condimentum id venenatis a condimentum vitae.',
          videoUrl: '',
          previewImageUrl: '',
          author: {
            id: 13,
            firstName: 'Марина',
            lastName: 'Вовк',
            avatar: 'https://i.pravatar.cc/300?img=5',
            bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
            mainInstitution: {
              id: 1,
              name: 'Адоніс',
              city: { id: 190, name: 'Київ' },
            },
          },
          directions: [
            {
              id: 1,
              name: 'covid-19',
              label: 'Covid-19',
              color: '#ef5350',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 3,
              name: 'surgery',
              label: 'Хірургія',
              color: '#7aebbf',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 2,
              name: 'ophthalmology',
              label: 'Офтальмологія',
              color: '#98ef50',
              hasDoctors: true,
              hasPosts: true,
            },
          ],
          tags: [],
          type: { id: 1, name: 'Стаття' },
          status: 'PUBLISHED',
          origins: [{ id: 2, name: 'Медитека', parameters: null }],
          createdAt: '16.02.2021',
          modifiedAt: '16.02.2021',
          publishedAt: '20.10.2021',
          importanceOrder: null,
          importantImageUrl: '',
          importantMobileImageUrl: '',
        },
        {
          id: 84,
          title: 'Tempus quam pellentesque',
          preview:
            'Ultrices sagittis orci a scelerisque purus semper eget. Arcu non odio euismod lacinia at',
          content:
            'Ultrices sagittis orci a scelerisque purus semper eget. Arcu non odio euismod lacinia at. Arcu bibendum at varius vel pharetra vel turpis nunc eget. Tempus quam pellentesque nec nam aliquam sem. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus.',
          videoUrl: '',
          previewImageUrl: '',
          author: {
            id: 14,
            firstName: 'Олег',
            lastName: 'Петренко',
            avatar: 'https://i.pravatar.cc/300?img=11',
            bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
            mainInstitution: {
              id: 5,
              name: 'Medical Idea',
              city: { id: 55, name: 'Бровари' },
            },
          },
          directions: [
            {
              id: 5,
              name: 'virology',
              label: 'Вірусологія',
              color: '#da80e8',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 7,
              name: 'pediatrics',
              label: 'Педіатрія',
              color: '#993333',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 6,
              name: 'cardiology',
              label: 'Кардіологія',
              color: '#00ffff',
              hasDoctors: true,
              hasPosts: true,
            },
          ],
          tags: [],
          type: { id: 1, name: 'Стаття' },
          status: 'PUBLISHED',
          origins: [{ id: 2, name: 'Медитека', parameters: null }],
          createdAt: '16.02.2021',
          modifiedAt: '16.02.2021',
          publishedAt: '20.10.2021',
          importanceOrder: null,
          importantImageUrl: '',
          importantMobileImageUrl: '',
        },
      ],
    },
    {
      fieldName: 'translation',
      postDTOS: [
        {
          id: 113,
          title:
            'авапвапвапвапвапfgdfgsdsfgsdfgsdfgsdfgsdfgsdfggfhdfghdfghdfghdfghdfgh',
          preview:
            'https://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpghttps://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-l',
          content:
            '<p>https://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpghttps://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpghttps://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpghttps://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpghttps://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpghttps://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpghttps://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpghttps://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpghttps://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpg</p>',
          videoUrl: null,
          previewImageUrl:
            'https://st2.depositphotos.com/1064024/10755/i/950/depositphotos_107559180-stock-photo-little-boy-illustration.jpg',
          author: {
            id: 35,
            firstName: 'Єва',
            lastName: 'Євенко',
            avatar: 'https://i.pravatar.cc/300?img=20',
            bio:
              'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat duis.',
            mainInstitution: {
              id: 5,
              name: 'Medical Idea',
              city: { id: 55, name: 'Бровари' },
            },
          },
          directions: [
            {
              id: 2,
              name: 'ophthalmology',
              label: 'Офтальмологія',
              color: '#98ef50',
              hasDoctors: true,
              hasPosts: true,
            },
          ],
          tags: [],
          type: { id: 1, name: 'Стаття' },
          status: 'PUBLISHED',
          origins: [{ id: 3, name: 'Переклад', parameters: null }],
          createdAt: '20.10.2021',
          modifiedAt: '20.10.2021',
          publishedAt: '20.10.2021',
          importanceOrder: null,
          importantImageUrl: '',
          importantMobileImageUrl: '',
        },
        {
          id: 88,
          title: 'Tempus quam pellentesque',
          preview:
            'Ultrices sagittis orci a scelerisque purus semper eget. Arcu non odio euismod lacinia at',
          content:
            'Ultrices sagittis orci a scelerisque purus semper eget. Arcu non odio euismod lacinia at. Arcu bibendum at varius vel pharetra vel turpis nunc eget. Tempus quam pellentesque nec nam aliquam sem. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus.',
          videoUrl: '',
          previewImageUrl: '',
          author: {
            id: 14,
            firstName: 'Олег',
            lastName: 'Петренко',
            avatar: 'https://i.pravatar.cc/300?img=11',
            bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
            mainInstitution: {
              id: 5,
              name: 'Medical Idea',
              city: { id: 55, name: 'Бровари' },
            },
          },
          directions: [
            {
              id: 1,
              name: 'covid-19',
              label: 'Covid-19',
              color: '#ef5350',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 3,
              name: 'surgery',
              label: 'Хірургія',
              color: '#7aebbf',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 2,
              name: 'ophthalmology',
              label: 'Офтальмологія',
              color: '#98ef50',
              hasDoctors: true,
              hasPosts: true,
            },
          ],
          tags: [],
          type: { id: 1, name: 'Стаття' },
          status: 'PUBLISHED',
          origins: [{ id: 3, name: 'Переклад', parameters: null }],
          createdAt: '16.02.2021',
          modifiedAt: '16.02.2021',
          publishedAt: '20.10.2021',
          importanceOrder: null,
          importantImageUrl: '',
          importantMobileImageUrl: '',
        },
        {
          id: 87,
          title: 'Proin nibh nisl condimentum',
          preview: 'Ullamcorper malesuada proin libero nunc consequat.',
          content:
            'Ullamcorper malesuada proin libero nunc consequat. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Leo in vitae turpis massa sed. Ultrices eros in cursus turpis.',
          videoUrl: '',
          previewImageUrl: '',
          author: {
            id: 15,
            firstName: 'Катерина',
            lastName: 'Кравченко',
            avatar: 'https://i.pravatar.cc/300?img=9',
            bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
            mainInstitution: {
              id: 2,
              name: 'Новий зір',
              city: { id: 190, name: 'Київ' },
            },
          },
          directions: [
            {
              id: 5,
              name: 'virology',
              label: 'Вірусологія',
              color: '#da80e8',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 7,
              name: 'pediatrics',
              label: 'Педіатрія',
              color: '#993333',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 6,
              name: 'cardiology',
              label: 'Кардіологія',
              color: '#00ffff',
              hasDoctors: true,
              hasPosts: true,
            },
          ],
          tags: [],
          type: { id: 1, name: 'Стаття' },
          status: 'PUBLISHED',
          origins: [{ id: 3, name: 'Переклад', parameters: null }],
          createdAt: '16.02.2021',
          modifiedAt: '16.02.2021',
          publishedAt: '20.10.2021',
          importanceOrder: null,
          importantImageUrl: '',
          importantMobileImageUrl: '',
        },
        {
          id: 86,
          title: 'Ultrices eros in cursus',
          preview:
            'Dolor sit amet consectetur adipiscing elit ut aliquam purus.',
          content:
            'Dolor sit amet consectetur adipiscing elit ut aliquam purus.',
          videoUrl: '',
          previewImageUrl: '',
          author: {
            id: 12,
            firstName: 'Степан',
            lastName: 'Степанов',
            avatar: 'https://i.pravatar.cc/300?img=12',
            bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
            mainInstitution: {
              id: 3,
              name: 'Інномед',
              city: { id: 81, name: 'Вінниця' },
            },
          },
          directions: [
            {
              id: 5,
              name: 'virology',
              label: 'Вірусологія',
              color: '#da80e8',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 6,
              name: 'cardiology',
              label: 'Кардіологія',
              color: '#00ffff',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 4,
              name: 'therapy',
              label: 'Терапія',
              color: '#ffee58',
              hasDoctors: true,
              hasPosts: true,
            },
          ],
          tags: [],
          type: { id: 1, name: 'Стаття' },
          status: 'PUBLISHED',
          origins: [{ id: 3, name: 'Переклад', parameters: null }],
          createdAt: '16.02.2021',
          modifiedAt: '16.02.2021',
          publishedAt: '20.10.2021',
          importanceOrder: null,
          importantImageUrl: '',
          importantMobileImageUrl: '',
        },
      ],
    },
    {
      fieldName: 'video',
      postDTOS: [
        {
          id: 112,
          title: 'erertewrtwertwertwertwertwertwertwertwertwert',
          preview:
            'https://www.youtube.com/embed/n79PMyqcCJ8https://www.youtube.com/embed/n79PMyqcCJ8https://www.youtube.com/embed/n79PMyqcCJ8',
          content:
            '<p>https://www.youtube.com/embed/n79PMyqcCJ8https://www.youtube.com/embed/n79PMyqcCJ8https://www.youtube.com/embed/n79PMyqcCJ8https://www.youtube.com/embed/n79PMyqcCJ8https://www.youtube.com/embed/n79PMyqcCJ8https://www.youtube.com/embed/n79PMyqcCJ8https://www.youtube.com/embed/n79PMyqcCJ8https://www.youtube.com/embed/n79PMyqcCJ8https://www.youtube.com/embed/n79PMyqcCJ8https://www.youtube.com/embed/n79PMyqcCJ8https://www.youtube.com/embed/n79PMyqcCJ8</p>',
          videoUrl: 'https://www.youtube.com/embed/n79PMyqcCJ8',
          previewImageUrl: null,
          author: {
            id: 35,
            firstName: 'Єва',
            lastName: 'Євенко',
            avatar: 'https://i.pravatar.cc/300?img=20',
            bio:
              'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat duis.',
            mainInstitution: {
              id: 5,
              name: 'Medical Idea',
              city: { id: 55, name: 'Бровари' },
            },
          },
          directions: [
            {
              id: 2,
              name: 'ophthalmology',
              label: 'Офтальмологія',
              color: '#98ef50',
              hasDoctors: true,
              hasPosts: true,
            },
          ],
          tags: [],
          type: { id: 2, name: 'Відео' },
          status: 'PUBLISHED',
          origins: [{ id: 1, name: 'Думка експерта', parameters: null }],
          createdAt: '20.10.2021',
          modifiedAt: '20.10.2021',
          publishedAt: '20.10.2021',
          importanceOrder: null,
          importantImageUrl: null,
        },
        {
          id: 10,
          title: 'Ultrices eros in cursus',
          preview: 'Fermentum iaculis',
          content:
            'Dolor sit amet consectetur adipiscing elit ut aliquam purus.',
          videoUrl: '',
          previewImageUrl: '',
          author: {
            id: 1,
            firstName: 'Таржеман',
            lastName: 'Соколов',
            avatar: 'https://i.pravatar.cc/300?img=70',
            bio:
              'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam q.',
            mainInstitution: {
              id: 1,
              name: 'Адоніс',
              city: { id: 190, name: 'Київ' },
            },
          },
          directions: [
            {
              id: 7,
              name: 'pediatrics',
              label: 'Педіатрія',
              color: '#993333',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 1,
              name: 'covid-19',
              label: 'Covid-19',
              color: '#ef5350',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 6,
              name: 'cardiology',
              label: 'Кардіологія',
              color: '#00ffff',
              hasDoctors: true,
              hasPosts: true,
            },
          ],
          tags: [
            { id: 1, tag: 'Профілактика' },
            { id: 6, tag: 'ЕКГ' },
            { id: 3, tag: 'Ковід' },
            { id: 5, tag: 'Міокард' },
          ],
          type: { id: 2, name: 'Відео' },
          status: 'PUBLISHED',
          origins: [{ id: 2, name: 'Медитека', parameters: null }],
          createdAt: '16.02.2021',
          modifiedAt: '16.02.2021',
          publishedAt: '20.10.2021',
          importanceOrder: null,
          importantImageUrl: '',
          importantMobileImageUrl: '',
        },
        {
          id: 7,
          title: 'Proin nibh nisl condimentum',
          preview: 'Fermentum iaculis',
          content:
            'Ullamcorper malesuada proin libero nunc consequat. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Leo in vitae turpis massa sed. Ultrices eros in cursus turpis.',
          videoUrl: '',
          previewImageUrl: '',
          author: {
            id: 1,
            firstName: 'Таржеман',
            lastName: 'Соколов',
            avatar: 'https://i.pravatar.cc/300?img=70',
            bio:
              'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam q.',
            mainInstitution: {
              id: 1,
              name: 'Адоніс',
              city: { id: 190, name: 'Київ' },
            },
          },
          directions: [
            {
              id: 5,
              name: 'virology',
              label: 'Вірусологія',
              color: '#da80e8',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 1,
              name: 'covid-19',
              label: 'Covid-19',
              color: '#ef5350',
              hasDoctors: true,
              hasPosts: true,
            },
            {
              id: 4,
              name: 'therapy',
              label: 'Терапія',
              color: '#ffee58',
              hasDoctors: true,
              hasPosts: true,
            },
          ],
          tags: [
            { id: 5, tag: 'Міокард' },
            { id: 4, tag: 'Допомога' },
          ],
          type: { id: 2, name: 'Відео' },
          status: 'PUBLISHED',
          origins: [{ id: 1, name: 'Думка експерта', parameters: null }],
          createdAt: '16.02.2021',
          modifiedAt: '16.02.2021',
          publishedAt: '20.10.2021',
          importanceOrder: null,
          importantImageUrl: '',
          importantMobileImageUrl: '',
        },
        {
          id: 110,
          title: 'COVID-19: як діти переживають пандемію',
          preview:
            "Жіноче здоров'я в контексті COVID-19. Ведення вагітних під час пандемії. Доказова медицина в акушерстві та гінекології.",
          content:
            '<h3>Жіноче здоров\'я в контексті COVID-19. Ведення вагітних під час пандемії. Доказова медицина в акушерстві та гінекології.</h3><p>Ці та інші теми Kateryna Bulavinova, медичний експерт ЮНІСЕФ, обговорює в інтерв\'ю з лікарем акушер-гінекологом, завідувачкою жіночої консультації Медичного центру Святої Параскеви, медичним блогером Наталією Лелюх.</p><h5><em>Пряма трансляція відбулася на Facebook сторінці </em><a rel=\\"noopener noreferrer\\" href=\\"https://www.facebook.com/UNICEFUkraine/\\">UNICEF Ukraine</a> <em>та YouTube каналі</em> <a rel=\\"noopener noreferrer\\" href=\\"https://www.youtube.com/channel/UCa24Vanhg1EZzP_Ov-ydDFg\\">Doctor Bulavinova&nbsp;</a></h5><h5><em>Дата та час трансляції: 21.11.2020</em></h5><h5><a rel=\\"noopener noreferrer\\" href=\\"https://www.unicef.org/ukraine/stories/navigating-pregnancy-during-covid-19-pandemic\\">Текстова версія інтерв\'ю</a></h5>',
          videoUrl: 'https://www.youtube.com/embed/49hPkCIz2y0',
          previewImageUrl: null,
          author: {
            id: 17,
            firstName: 'Олена',
            lastName: 'Шевченко',
            avatar: 'https://i.pravatar.cc/300?img=1',
            bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
            mainInstitution: {
              id: 1,
              name: 'Адоніс',
              city: { id: 190, name: 'Київ' },
            },
          },
          directions: [
            {
              id: 1,
              name: 'covid-19',
              label: 'Covid-19',
              color: '#ef5350',
              hasDoctors: true,
              hasPosts: true,
            },
          ],
          tags: [],
          type: { id: 2, name: 'Відео' },
          status: 'PUBLISHED',
          origins: [{ id: 1, name: 'Думка експерта', parameters: null }],
          createdAt: '06.08.2021',
          modifiedAt: '06.08.2021',
          publishedAt: '06.08.2021',
          importanceOrder: null,
          importantImageUrl: '',
          importantMobileImageUrl: '',
        },
      ],
    },
  ],
  pageable: 'INSTANCE',
  totalPages: 1,
  totalElements: 4,
  last: true,
  number: 0,
  sort: { sorted: false, unsorted: true, empty: true },
  size: 4,
  first: true,
  numberOfElements: 4,
  empty: false,
};
