name: Dokazovi-fe Release

on:
  push:
    branches:
      - release
      - feature/ci-alignments

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build the tagged Docker image
        run: >
          docker build -f Dockerfile.prod
          --build-arg REACT_APP_IMGUR_CLIENT_ID=${{ secrets.REACT_APP_IMGUR_CLIENT_ID }}
          --build-arg REACT_APP_GOOGLE_ID=${{ secrets.REACT_APP_GOOGLE_ID }}
          --build-arg REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}
          -t dokazovi_fe .
      - name: Deploy on heroku
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          docker_compose_file: 'docker-compose.prod.yml'
          heroku_apps: '[{"imagename":"dokazovi_fe","appname":"dokazovi-fe-release","apptype":"web"}]'
